### ISSUE TITLE
Curation of CNVs

### ISSUE THREAD

**Issue by GeorgetteTanner** [yuchaojiang/Canopy#11]
Hi

I'm wanting to use Canopy to generate the cancer cell fractions of SNVs in matched primary and recurrent tumours. However I have samples from 50+ patients so its not overly feasible for me to manually curate the inputs for each one. 

If I understand your instructions correctly, it seems like it would be possible to write a script to create the overlap matrix C for each patient by going through each listed region and identifying CNAs that overlap it, instead of requiring manual inspection. Is that right, or have I misunderstood the instructions?

In your example in "How do I generate CNA input for Canopy?" and the vignette, the regions in matrix C are given as whole chromosomes which confused me. Is that just because only whole chromosome CNAs have occurred in that example? 

Also, the instructions say that "It is also worth noting that additional steps are further neede to generate curated CNA segments. For example, chr17q is split into three segments in the primary tumor, which should be just one large duplication instead (via comparison against the relapse)". 
This would be difficult to do on samples for 50+ patients - would it be feasible to leave this step out, or is that really not recommended to do ever, even if I'm only interested in the cancer cell fraction and not the phylogeny reconstruction?

Lastly, when editing break points for the same CNA between two samples so that they match, what sort of margin of error would you recommend allowing to consider CNAs to be the same? 

Thanks for any help!

**Comment by yuchaojiang** [comment]
I'm wanting to use Canopy to generate the cancer cell fractions of SNVs in matched primary and recurrent tumours. However I have samples from 50+ patients so its not overly feasible for me to manually curate the inputs for each one.

If I understand your instructions correctly, it seems like it would be possible to write a script to create the overlap matrix C for each patient by going through each listed region and identifying CNAs that overlap it, instead of requiring manual inspection. Is that right, or have I misunderstood the instructions?

**Yes, it is possible however this part has not been implemented in Canopy yet. We gave a prototype algorithm in Supplementary Figure S3 in our PNAS paper for illustration. However, this is very sensitive to noise (in calling the copy number segments) and is very error-prone. This is, on the other hand, also very important since they are used as input for Canopy and any error at this stage would lead to a garbage-in-garbage-out scenario. Therefore we recommend careful pruning and manual inspection.** 

In your example in "How do I generate CNA input for Canopy?" and the vignette, the regions in matrix C are given as whole chromosomes which confused me. Is that just because only whole chromosome CNAs have occurred in that example?

**Sorry for the confusion. It's only used as a name for the CNA event in the matrices. You can name it as CNA1, CNA2, etc. After inference, the name will be tagged with _LOH, _dup, or _del according to the posterior copy number estimates.**

Also, the instructions say that "It is also worth noting that additional steps are further neede to generate curated CNA segments. For example, chr17q is split into three segments in the primary tumor, which should be just one large duplication instead (via comparison against the relapse)".
This would be difficult to do on samples for 50+ patients - would it be feasible to leave this step out, or is that really not recommended to do ever, even if I'm only interested in the cancer cell fraction and not the phylogeny reconstruction?

**Again, the upstream input is very important. If there are multiple segments that seem to belong to the same copy number event, I would recommend merging them. Otherwise, larger computation burden is one issue and more importantly, there will be issues with breakpoints merging and calling overlapping copy number events.**

Lastly, when editing break points for the same CNA between two samples so that they match, what sort of margin of error would you recommend allowing to consider CNAs to be the same?

**Sorry it's hard to tell without looking at the data. I would say set a threshold based on their genomic location? Visualization is very important and at this stage we recommend focusing on large chromosome-arm level copy number changes.**

**Additionally, I just wanted to mention that to solve the overlapping CNA issue is non-trivial, especially in the bulk sequencing setting where everything bulk measurement is a mean across different populations. I would recommend starting with a small scale Canopy run using good quality CNA calls from a few chromosomes.**
