### ISSUE TITLE
how to run parallel in the step of canopy.sample

### ISSUE THREAD

**Issue by daisyyr** [yuchaojiang/Canopy#12]
Hi~Thanks for developing such an useful tool!
Since the step `sampchain = canopy.sample(R = R, X = X, WM = WM, Wm = Wm, epsilonM = epsilonM, 
                          epsilonm = epsilonm, C = C, Y = Y, K = K, 
                          numchain = numchain, max.simrun = 100000,
                          min.simrun = 20000, writeskip = 200,
                          projectname = projectname, cell.line = TRUE,
                          plot.likelihood = TRUE)` is time-consuming, I wonder if I could run this step parallely and use multiple threads.
Looking forward to your reply!

**Comment by yuchaojiang** [comment]
Hi,

You can specify a small numchain, and run this in parallel on different computing nodes.

Yuchao

On Apr 12, 2022, at 1:02 PM, daisyyr ***@***.******@***.***>> wrote:



Hi~Thanks for developing such an useful tool!
Since the step sampchain = canopy.sample(R = R, X = X, WM = WM, Wm = Wm, epsilonM = epsilonM, epsilonm = epsilonm, C = C, Y = Y, K = K, numchain = numchain, max.simrun = 100000, min.simrun = 20000, writeskip = 200, projectname = projectname, cell.line = TRUE, plot.likelihood = TRUE) is time-consuming, I wonder if I could run this step parallely and use multiple threads.
Looking forward to your reply!

**Comment by daisyyr** [comment]
Thanks for your reply!
Did you mean that the running the step `sampchain = canopy.sample(R = R, X = X, WM = WM, Wm = Wm, epsilonM = epsilonM, epsilonm = epsilonm, C = C, Y = Y, K = K, numchain = 5, max.simrun = 100000, min.simrun = 20000, writeskip = 200, projectname = projectname, cell.line = TRUE, plot.likelihood = TRUE)`  for 4 times on different threads equals to `sampchain = canopy.sample(R = R, X = X, WM = WM, Wm = Wm, epsilonM = epsilonM, epsilonm = epsilonm, C = C, Y = Y, K = K, numchain = 20, max.simrun = 100000, min.simrun = 20000, writeskip = 200, projectname = projectname, cell.line = TRUE, plot.likelihood = TRUE)`?
And how can I integrate these results?

**Comment by yuchaojiang** [comment]
Hi Sorry for my late reply
You will need to write a script to combine the posterior samples.
You can refer to the vignettes on how to get the posterior estimates from one run, and from there, it's just to combine them from different runs.
